[project]
name = "nde"
version = "0.1.0"
description = "A minimal Python project"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
